name: jsigen
description: A starting point for Dart libraries or applications.
version: 0.0.1-pre
repository: https://github.com/nikeokoronkwo/dart_catalog

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
