name: wai
description: >-
  WebAssembly Interface for Working with WebAssembly and interoping with other languages via WebAssembly
version: 1.0.0
repository: https://github.com/nikeokoronkwo/dart_catalog

environment:
  sdk: '>=3.3.0'

# Add regular dependencies here.
dependencies:
  js: ^0.7.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
